#cloud-config
users:
  - name: vader
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICixC3a5ECjM//PDxwZ70byGT1AOyk4cKKGhqkCBHm1p m93p
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFPGSjUtdW0/2kgi9CY0/UILp67FohD/50s9KoFtYAsT magnapi
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJBxv+NZ/P0pw3inXpqffaV5GB3FShqzZ8ovP6nHJ2I4 m1
packages:
  - ufw
  - curl 
  - git 
  - zsh 
  - docker-compose 
  - restic
  - tmux
  - make 
  - imagemagick
package_update: true
package_upgrade: true
runcmd:
  - su -c 'echo "cloud-init start - $(date)" >> ~/cloud-init.txt' - vader
  - curl -fsSL https://get.docker.com | sh
  - usermod -aG docker vader
  - restic self-update
  #- apt-get install -y automake libtool g++ protobuf-compiler libprotobuf-dev libboost-dev libutempter-dev libncurses5-dev zlib1g-dev libio-pty-perl libssl-dev pkg-config
  #- git clone https://github.com/keithw/mosh.git && cd mosh && ./autogen.sh && ./configure && make && make install
  #- rm -rf mosh
  - su -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended' - vader
  - su -c 'git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.oh-my-zsh/custom/themes/powerlevel10k' - vader
  - su -c 'echo "source $HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme" >> ~/.zshrc' - vader
  - su -c "sed -i 's/ZSH_THEME\=.*/ZSH_THEME=\"powerlevel10k\/powerlevel10k\"/' ~/.zshrc" - vader
  - su -c 'sudo chsh -s $(which zsh) $(whoami)' - vader
  - su -c 'touch ~/.hushlogin' - vader
  - su -c 'git clone https://github.com/dylanaraps/neofetch ~/neofetch' - vader
  - su -c 'cd ~/neofetch && sudo make install && rm -rf ~/neofetch' - vader
  - su -c 'wget https://raw.githubusercontent.com/oregonpillow/powerlevel10k/master/.p10k.zsh -O ~/.p10k.zsh' - vader 
  - su -c 'wget https://raw.githubusercontent.com/oregonpillow/powerlevel10k/master/girl.jpg -O ~/.neofetch_image.jpg' - vader
  - su -c 'echo "\n[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh" >> ~/.zshrc' - vader
  - su -c 'echo "\nneofetch --iterm2 --source ~/.neofetch_image.jpg" >> ~/.zshrc' - vader
  - su -c 'echo "\nLC_CTYPE=en_US.UTF-8" >> ~/.zshrc' - vader
  - su -c 'echo "LC_ALL=en_US.UTF-8" >> ~/.zshrc' - vader
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -E 's/#?Port 22/Port 14999/' /etc/ssh/sshd_config
  - ufw allow 14999/tcp
  #- ufw allow 60000/udp
  - ufw enable
  - systemctl restart sshd
  - su -c 'echo "cloud-init complete - $(date)" >> ~/cloud-init.txt' - vader
